version: "3.9"

services:
 laravelapp:
    container_name: laravelapp
    image: devmarcosav/laravelapp:2.2.3
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
 db:
    container_name: db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: db_veiculos_user
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: db_veiculos
    volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
 pgdata: {}
