version: "3.9"

services:
 laravelapp:
    container_name: laravelapp
    image: devmarcosav/laravelapp:2.2.3
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

 db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
 pgdata: {}